### ISSUE TITLE
BUG : Plane mirrors are reflecting from silvered surfaces.

### ISSUE THREAD

**Issue by datavorous** [KineticTactic/light-playground#1]
Allow plane mirrors to reflect only from one side. 
Moreover, grid snapping would be beneficial for accurate simulations.
Screenshot: 
![reflecta_screenshot (1)](https://github.com/user-attachments/assets/26cf1c8f-9788-493f-b6af-600b1781e5f6)

**Comment by KineticTactic** [comment]
So should the rays that hit the backside just get absorbed? I think then I can add a "Double sided" checkbox that is disabled by default.

**Comment by KineticTactic** [comment]
Also basic grid snapping exists if you enable "Show grid" and hold control while moving/rotating stuff. Do you have any ideas for improvement?

**Comment by datavorous** [comment]
> So should the rays that hit the backside just get absorbed? I think then I can add a "Double sided" checkbox that is disabled by default.

Yes

**Comment by datavorous** [comment]
> Also basic grid snapping exists if you enable "Show grid" and hold control while moving/rotating stuff. Do you have any ideas for improvement?

Maybe add an option to enable snapping the entities to the nearest grid lines intersection, would be helpful for mobile devices. Very much needed for when measurements are at stake.

**Comment by KineticTactic** [comment]
> Maybe add an option to enable snapping the entities to the nearest grid lines intersection, would be helpful for mobile devices. Very much needed for when measurements are at stake.

Alright, that sounds good, I'll implement that.

**Comment by KineticTactic** [comment]
This has been implemented in c10d46e.
